"""The OAuth seam: authorize, exchange, refresh, revoke — with a fake, and no real client.

Every platform in ``docs/CHANNELS.md`` §2 that we could publish to uses the same four
operations, in the same order, with the same failure modes. So this is one port with one
fake behind it, and a real adapter per platform is added the day that platform's App
Review is actually approved.

**One real adapter now exists — :mod:`platform_oauth_meta`, for ``facebook`` and
``instagram`` — and it changes nothing about what may be PUBLISHED.** ``docs/CHANNELS.md``
§2-3 is unchanged and still explicit: Facebook Page and Instagram publishing need Meta App
Review (screencast, privacy policy, business verification, two to six weeks, refusable by
form letter); LinkedIn company-page posting needs Marketing Developer Platform approval;
TikTok's unaudited apps are confined to private/self-only visibility. So what the Meta
adapter buys is precisely the CONNECTION lifecycle against the live platform — a real
consent dialog, a real long-lived credential, a real renewal, a real de-authorisation —
and :func:`oauth_status` says both halves out loud, because a screen that reports "real
provider" without reporting "publishing is still in somebody else's queue" is a support
ticket.

**No LinkedIn or TikTok client is written here, and that is still a decision rather than a
gap.** A client written against those APIs today could not be exercised end to end — not
by a test (this suite makes no network calls, ever) and not by hand (there is no approved
app to authenticate against). It would be untested code shaped like a feature, which is
worse than an honest absence, because the absence is visible and the untested code is not.
The Meta adapter is subject to the same limit and does not pretend otherwise: every path
in it is proven against an injected ``httpx.MockTransport``, and the first real
round-trip happens the day somebody sets ``META_APP_ID`` and ``META_APP_SECRET``.

What IS buildable now, and what the rest of the system is waiting on, is this shape:

* an authorization URL a human can be sent to,
* a code-for-token exchange that yields a credential with an expiry and a scope list,
* a refresh, because every one of these tokens expires and an integration that cannot
  renew is an integration that breaks quietly a month after it is set up,
* a revoke, so disconnecting means something on the platform's side and not just in our
  database.

:class:`FakeOAuthProvider` implements all four with no I/O, which is what makes the whole
connect → expire → refresh → revoke lifecycle testable today. It follows the same rule
the model router follows and ``CLAUDE.md`` states: a missing credential means the fake,
plus a status that says so — never a silent no-op and never a claim that something
happened outside this process.

The one piece a fake provider cannot fake by itself is the CONSENT SCREEN, and without it
the lifecycle above was reachable only from a test. The authorization URL used to point at
``fake-oauth.invalid`` — RFC 2606 reserved, so it can never resolve — which meant a human
could start a connect and never finish one: the browser had nowhere to go, so the callback
was never called, so no connection could be created from the UI at all. That is what
:func:`fake_consent_path` fixes. A fake provider's authorization URL now points at a
stand-in consent screen served by ``api/connections.py`` **on our own origin**, carrying
the same ``redirect_uri`` and ``state`` a platform would have been handed, and that screen
sends the browser back to ``redirect_uri`` with a code and the state it was given.

**This is a stand-in, not a bypass, and the distinction is mechanical rather than a
promise.** The ``state`` cookie is written by ``POST /connect`` on our origin, the browser
holds it, and the callback is on that same origin — so the cookie is presented by the
browser in the ordinary way and ``api/oauth_state.verify_state`` plus
``nonce_matches`` run exactly as designed, against a nonce that travelled through the URL
and not through the cookie. Nothing is forged, nothing is skipped, and a callback whose
``state`` does not match is refused after this change exactly as it was before it. A fake
provider standing in for a third party is what a fake provider IS; the unreachable
``.invalid`` URL was standing in for a consent screen that does not exist, and this
replaces it with one that does.

The state parameter is generated by the caller (``connection_service.begin_connect``) and
is NOT stored here. This module holds no session and no database; a provider that
remembered state would be a provider with a side effect, and there would then be two
places that decide whether a callback is genuine.
"""

from __future__ import annotations

import os
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Final, Protocol, final
from urllib.parse import urlencode, urlsplit

from backend.app.core.token_cipher import Secret

__all__ = [
    "CONNECTABLE_PLATFORMS",
    "FAKE_CONSENT_PATH_TEMPLATE",
    "PLATFORM_SCOPES",
    "FakeOAuthProvider",
    "OAuthError",
    "OAuthProvider",
    "OAuthStatus",
    "TokenGrant",
    "fake_consent_path",
    "get_oauth_provider",
    "oauth_status",
    "real_oauth_platforms",
]

#: The platforms a connection row may name. Closed, and widening it is a migration
#: (``platform_connections`` has a CHECK constraint on the same list) — deliberately,
#: because a typo'd platform is a connection nobody can ever publish through, and a
#: constraint is how that becomes an insert failure instead of a support ticket.
#:
#: Sourced from ``docs/CHANNELS.md`` §2. ``x`` is absent because posting there sits
#: behind a paid tier and the same document rules it export-only; ``google_ads`` is
#: absent because it spends money and is assets-only by decision.
CONNECTABLE_PLATFORMS: Final[tuple[str, ...]] = (
    "facebook",
    "instagram",
    "linkedin",
    "tiktok",
    "youtube",
    "google_business",
)

#: The scopes each platform's publish path requires, per ``docs/CHANNELS.md`` §2. Kept
#: here rather than at a call site so that "what did we ask for" and "what were we
#: granted" are comparable — a token issued with a subset of these is the usual reason a
#: publish call fails with a permissions error long after the connection looked fine.
PLATFORM_SCOPES: Final[Mapping[str, tuple[str, ...]]] = {
    "facebook": ("pages_manage_posts", "pages_read_engagement"),
    "instagram": ("instagram_content_publish", "instagram_basic"),
    "linkedin": ("w_member_social",),
    "tiktok": ("video.upload",),
    "youtube": ("https://www.googleapis.com/auth/youtube.upload",),
    "google_business": ("https://www.googleapis.com/auth/business.manage",),
}

#: How long a fake credential lasts. An hour, because that is roughly what the real
#: short-lived tokens are, and because a lifetime long enough to never expire during a
#: test is a lifetime that makes the expiry path untested.
FAKE_TOKEN_LIFETIME: Final = timedelta(hours=1)

#: Where a fake provider sends the human: a stand-in consent screen served by
#: ``api/connections.py`` on our own origin. See that module's ``simulated_consent``.
#:
#: ``{platform}`` is a PATH segment and not a query parameter deliberately: the route has
#: to be able to look up the provider for that platform and refuse to render at all unless
#: it is the fake one, and a path parameter is the form FastAPI will hand it before any
#: query parsing. It is written here rather than in the router because this is the module
#: that mints the URL, and ``api/connections.py`` derives its route path from this constant
#: so the two cannot drift into pointing at different places.
FAKE_CONSENT_PATH_TEMPLATE: Final = "/api/v1/connections/{platform}/simulated-consent"

#: The fallback authorization base, used only when there is no absolute ``redirect_uri`` to
#: take an origin from — a caller passing a relative one, which no route here does.
#: ``.invalid`` is reserved by RFC 2606 and can never resolve, so a URL that leaks into a
#: browser or a fixture cannot reach a real service. It is a fallback rather than the
#: default precisely because an unreachable consent screen is what made a connect
#: impossible to complete; see the module docstring.
_FAKE_AUTHORIZE_BASE: Final = "https://fake-oauth.invalid/authorize"


def fake_consent_path(platform: str) -> str:
    """The path of the stand-in consent screen for ``platform``."""
    return FAKE_CONSENT_PATH_TEMPLATE.format(platform=platform)


def _origin_of(url: str) -> str:
    """``scheme://host[:port]`` of an absolute URL, or ``""``.

    The consent screen has to live on the same origin as the callback — that is what makes
    the ``state`` cookie present itself normally on the way back, and therefore what makes
    the CSRF control run rather than be worked around. So the origin is taken from the
    ``redirect_uri`` the caller already computed from configuration
    (``api/connections._redirect_uri``) rather than read from a request header, which would
    let a poisoned ``Host`` choose where a human is sent.
    """
    parts = urlsplit(url)
    if not parts.scheme or not parts.netloc:
        return ""
    return f"{parts.scheme}://{parts.netloc}"


class OAuthError(Exception):
    """A provider operation failed.

    ``retryable`` mirrors ``ActuatorError``'s field and for the same reason: a rate limit
    or a 502 is worth another attempt, a rejected refresh token never is, and treating
    them alike either gives up on a blip or hammers a permanent failure. The caller
    translates this into a connection status, not into a stack trace.
    """

    def __init__(self, message: str, *, retryable: bool = False) -> None:
        super().__init__(message)
        self.retryable = retryable


@dataclass(frozen=True, slots=True)
class TokenGrant:
    """What a successful exchange or refresh returns.

    The credentials are :class:`Secret`, so this dataclass's generated ``repr`` — which
    is what a log line or a traceback would print — carries masked values rather than
    live tokens.

    ``expires_at`` is nullable because some platforms issue a long-lived token with no
    stated expiry. ``None`` means "no expiry known", NOT "never expires", and
    ``ConnectionView`` treats it that way: it cannot be expired by the clock, only by the
    platform rejecting it.
    """

    external_account_id: str
    access_token: Secret
    refresh_token: Secret | None = None
    expires_at: datetime | None = None
    scopes: tuple[str, ...] = ()
    external_account_name: str | None = None
    #: True when the grant came from the fake provider. Carried so a connection made
    #: without a real platform app cannot be mistaken for one that was.
    fake: bool = False


class OAuthProvider(Protocol):
    """One platform's OAuth implementation.

    Deliberately four methods and no persistence: whose connection this is, where the
    envelope goes, and what the row says are ``connection_service``'s concerns. A
    provider that also stored things would be a provider that has to be mocked to test
    anything at all.
    """

    @property
    def platform(self) -> str:
        """Which of :data:`CONNECTABLE_PLATFORMS` this speaks for."""
        ...

    @property
    def fake(self) -> bool:
        """True when no real platform app is configured behind it."""
        ...

    def authorization_url(self, *, redirect_uri: str, state: str, scopes: Sequence[str]) -> str:
        """Where to send the human. Pure — no request is made by asking for this."""
        ...

    async def exchange_code(self, *, code: str, redirect_uri: str) -> TokenGrant:
        """Trade a callback code for a credential. Raise :class:`OAuthError` on failure."""
        ...

    async def refresh(self, refresh_token: Secret) -> TokenGrant:
        """Renew an expiring credential. Raise :class:`OAuthError` if it is not renewable."""
        ...

    async def revoke(self, credential: Secret) -> None:
        """Tell the platform to forget this credential. Idempotent."""
        ...


@final
class FakeOAuthProvider:
    """A complete OAuth lifecycle with no network, deterministic enough to assert on.

    Two behaviours are load-bearing for the tests that use it:

    * **a refresh returns a DIFFERENT access token.** A fake that handed back the same
      string would let "refresh rewrote the row" pass while nothing was rewritten.
    * **a revoked or unknown refresh token raises.** That is the real failure this
      lifecycle has to handle — a user who removed our app from their account — and
      without it the refresh path would only ever be tested on its happy branch.

    ``clock`` is injected because expiry is the whole point of the refresh path, and a
    test that has to sleep for an hour to reach it is a test nobody runs.
    """

    def __init__(
        self,
        platform: str,
        *,
        clock: Callable[[], datetime] | None = None,
        lifetime: timedelta = FAKE_TOKEN_LIFETIME,
        granted_scopes: Sequence[str] | None = None,
        account_id: str = "fake-account",
        account_name: str | None = "Fake Account",
    ) -> None:
        if platform not in CONNECTABLE_PLATFORMS:
            raise ValueError(
                f"unknown platform {platform!r}. Known: {', '.join(CONNECTABLE_PLATFORMS)}."
            )
        self._platform = platform
        self._now = clock if clock is not None else _utc_now
        self._lifetime = lifetime
        self._granted = tuple(granted_scopes) if granted_scopes is not None else None
        self._account_id = account_id
        self._account_name = account_name
        self._issued = 0
        self._live_refresh_tokens: set[str] = set()
        self._revoked: set[str] = set()

    @property
    def platform(self) -> str:
        return self._platform

    @property
    def fake(self) -> bool:
        return True

    def authorization_url(self, *, redirect_uri: str, state: str, scopes: Sequence[str]) -> str:
        """The stand-in consent screen's URL, carrying what a platform would be handed.

        The parameters are the real OAuth ones — ``client_id``, ``redirect_uri``,
        ``response_type``, ``scope``, ``state`` — because the point of a fake is that the
        shape around it is the shape a real adapter will slot into. ``state`` travelling in
        this URL is load-bearing: the consent screen echoes it back from the query string,
        the browser presents the signed cookie itself, and the callback compares the two.
        A consent screen that read the nonce out of the cookie instead would be comparing
        the cookie against itself, which is the bypass this deliberately is not.
        """
        query = urlencode(
            {
                "client_id": f"fake-{self._platform}-app",
                "redirect_uri": redirect_uri,
                "response_type": "code",
                "scope": " ".join(scopes),
                "state": state,
            }
        )
        origin = _origin_of(redirect_uri)
        if not origin:
            return f"{_FAKE_AUTHORIZE_BASE}?{query}"
        return f"{origin}{fake_consent_path(self._platform)}?{query}"

    async def exchange_code(self, *, code: str, redirect_uri: str) -> TokenGrant:
        if not code.strip():
            raise OAuthError("the callback carried no authorization code")
        return self._issue()

    async def refresh(self, refresh_token: Secret) -> TokenGrant:
        raw = refresh_token.reveal()
        if raw in self._revoked:
            raise OAuthError(
                "this credential was revoked at the platform; the business has to "
                "reconnect the account"
            )
        if raw not in self._live_refresh_tokens:
            raise OAuthError("unknown refresh token")
        # A real provider rotates the refresh token too, and a client that kept using
        # the old one breaks on the second renewal rather than the first.
        self._live_refresh_tokens.discard(raw)
        return self._issue()

    async def revoke(self, credential: Secret) -> None:
        raw = credential.reveal()
        self._revoked.add(raw)
        self._live_refresh_tokens.discard(raw)

    def _issue(self) -> TokenGrant:
        self._issued += 1
        serial = self._issued
        refresh = f"fake-refresh-{self._platform}-{serial}"
        self._live_refresh_tokens.add(refresh)
        scopes = self._granted if self._granted is not None else PLATFORM_SCOPES[self._platform]
        return TokenGrant(
            external_account_id=self._account_id,
            access_token=Secret(f"fake-access-{self._platform}-{serial}"),
            refresh_token=Secret(refresh),
            expires_at=self._now() + self._lifetime,
            scopes=tuple(scopes),
            external_account_name=self._account_name,
            fake=True,
        )


def _utc_now() -> datetime:
    return datetime.now(UTC)


@dataclass(frozen=True, slots=True)
class OAuthStatus:
    """Which platforms could really be connected, and why not.

    Same job as ``llm.router.config_status``: a screen that says "connect Instagram"
    without saying that publishing there is waiting on somebody else's approval queue is
    a screen that generates a support ticket.
    """

    platforms: tuple[str, ...]
    real_providers: tuple[str, ...] = ()
    using_fake_providers: bool = True
    message: str = ""
    blocked_on_app_review: tuple[str, ...] = field(default_factory=tuple)


#: The platforms whose publish permission is somebody else's approval queue, per
#: ``docs/CHANNELS.md`` §2-3. Named so a UI can say so rather than implying the delay is
#: ours.
APP_REVIEW_GATED: Final[tuple[str, ...]] = (
    "facebook",
    "instagram",
    "linkedin",
    "tiktok",
)


def get_oauth_provider(platform: str, env: Mapping[str, str] | None = None) -> OAuthProvider:
    """The provider for ``platform``.

    Selection is by CREDENTIAL and by nothing else — no flag, no setting, no separate
    "enable Meta" switch that could disagree with whether an app is configured. That is
    the same rule ``actuators/email.build_email_actuator`` and ``llm.router`` follow, and
    it is why a machine with no credential cannot accidentally be pointed at a real
    platform.

    Two real adapters exist: :mod:`platform_oauth_meta` for ``facebook`` and
    ``instagram`` (both ``META_APP_ID`` and ``META_APP_SECRET`` required), and
    :mod:`platform_oauth_linkedin` for ``linkedin`` (both ``LINKEDIN_CLIENT_ID`` and
    ``LINKEDIN_CLIENT_SECRET``). TikTok, YouTube and Google Business Profile are still
    the fake, for the reasons in the module docstring.

    The import is inside the function because ``platform_oauth_meta`` imports
    :class:`OAuthError` and :class:`TokenGrant` from here: a module-level import would be
    a cycle. It also keeps ``httpx`` out of this module's import graph, so a caller that
    only wants :class:`FakeOAuthProvider` pays nothing for the real one.
    """
    from backend.app.services.platform_oauth_linkedin import build_linkedin_provider
    from backend.app.services.platform_oauth_meta import build_meta_provider

    environ = env if env is not None else os.environ
    # Each builder answers `None` for a platform it does not speak for, so the order is
    # not a precedence rule — no two builders claim the same platform, and a `for` loop
    # over them would read as though one could shadow another.
    real = build_meta_provider(platform, environ) or build_linkedin_provider(platform, environ)
    if real is not None:
        return real
    return FakeOAuthProvider(platform)


def real_oauth_platforms(env: Mapping[str, str] | None = None) -> tuple[str, ...]:
    """Which of :data:`CONNECTABLE_PLATFORMS` have a real adapter AND its credentials.

    Derived by asking :func:`get_oauth_provider` rather than by re-reading the
    environment, so the list a screen shows cannot disagree with the provider a connect
    actually uses — the failure being prevented is a settings page that says "Facebook is
    live" while the callback is being served by the fake.
    """
    environ = env if env is not None else os.environ
    return tuple(
        platform
        for platform in CONNECTABLE_PLATFORMS
        if not get_oauth_provider(platform, environ).fake
    )


def oauth_status(env: Mapping[str, str] | None = None) -> OAuthStatus:
    """Report what connecting a platform would actually do right now.

    ``env`` is optional so the routes can keep calling this with no arguments; a test
    that wants a configured app passes ``env={...}``, which is how every provider seam in
    this project is written (``tests/conftest.py`` strips the real variables).
    """
    real = real_oauth_platforms(env)
    fake = tuple(platform for platform in CONNECTABLE_PLATFORMS if platform not in real)

    if not real:
        message = (
            "No real platform OAuth adapter is configured, so every connection is made "
            "against FakeOAuthProvider (no network) and nothing can be published "
            "outside this process. Publishing to "
            + ", ".join(APP_REVIEW_GATED)
            + " is gated on per-platform App Review -- see docs/CHANNELS.md sections 2-3."
        )
    else:
        # Two sentences, and the second one is the important one: a real adapter means a
        # customer's grant is real, NOT that we may post with it. Saying only the first
        # half is how a settings screen starts promising something App Review has not
        # granted yet.
        message = (
            "A real OAuth adapter is configured for "
            + ", ".join(real)
            + ", so connecting one of those authorises us against the live platform and "
            "the credential we store is real. Publishing is still gated on per-platform "
            "App Review (" + ", ".join(APP_REVIEW_GATED) + ") -- see docs/CHANNELS.md "
            "sections 2-3."
        )
        if fake:
            message += " Every other platform (" + ", ".join(fake) + ") still uses "
            message += "FakeOAuthProvider: no network, nothing published."

    return OAuthStatus(
        platforms=CONNECTABLE_PLATFORMS,
        real_providers=real,
        using_fake_providers=bool(fake),
        blocked_on_app_review=APP_REVIEW_GATED,
        message=message,
    )
