"""Declarative base and the column conventions every table follows.

Two conventions are enforced structurally rather than by review:

* every table carries ``created_at`` / ``updated_at``;
* every *business-scoped* table carries ``business_id``, because tenant isolation
  is a schema property here, not a convention -- see docs/ARCHITECTURE.md section 6.

Naming conventions are declared on the metadata so Alembic emits stable,
predictable constraint names. Without this, autogenerate produces unnamed
constraints that later migrations cannot drop by name.
"""

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every model in the application."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """``created_at`` / ``updated_at``, maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UuidPkMixin:
    """UUID primary key, generated by the application.

    Application-side generation rather than ``gen_random_uuid()`` so an object
    has an id before it is flushed -- which the agent runtime needs in order to
    build an idempotency key before the row exists.
    """

    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid4)


class BusinessScopedMixin:
    """Marks a table as belonging to exactly one business.

    Row-level security policies key off this column, and
    ``tests/db/test_tenant_isolation.py`` asserts that a second business reads
    zero rows from every table that uses this mixin. Adding a business-scoped
    table without this mixin is therefore a test failure, not a review comment.
    """

    business_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
