"""user role

Revision ID: 1fc3f48597dc
Revises: 5e08c8bea18d
Create Date: 2026-08-19 13:21:59.592362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fc3f48597dc"
down_revision: Union[str, Sequence[str], None] = "5e08c8bea18d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.String(length=32), server_default="owner", nullable=False)
    )
    op.create_check_constraint(
        op.f("ck_users_role_valid"), "users", "role in ('member','owner','platform_admin')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_role_valid"), "users", type_="check")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
