"""phase 1-6 core schema

Revision ID: 3b8336ae2975
Revises:
Create Date: 2026-08-18 21:25:07.928581

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b8336ae2975"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before the kb_chunks.embedding column is created.
    # IF NOT EXISTS keeps this idempotent on a database where an operator
    # enabled it by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "businesses",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=2048), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("dna", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_businesses_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
    )
    op.create_index(op.f("ix_businesses_owner_id"), "businesses", ["owner_id"], unique=False)
    op.create_table(
        "crawl_pages",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("canonical", sa.String(length=2048), nullable=True),
        sa.Column("h_tree", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("jsonld", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_crawl_pages_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_pages")),
    )
    op.create_index(
        op.f("ix_crawl_pages_business_id"), "crawl_pages", ["business_id"], unique=False
    )
    op.create_index(
        "ix_crawl_pages_business_id_url", "crawl_pages", ["business_id", "url"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("extraction_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending','processing','indexed','failed','no_text')",
            name=op.f("ck_documents_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_documents_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_business_id"), "documents", ["business_id"], unique=False)
    op.create_table(
        "opportunities",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("target_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_impact", sa.String(length=16), nullable=False),
        sa.Column("effort", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_opportunities_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        op.f("ix_opportunities_business_id"), "opportunities", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_opportunities_score"), "opportunities", ["score"], unique=False)
    op.create_table(
        "runs",
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("current_node", sa.String(length=32), nullable=True),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("budget_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("used_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("resumed_count", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("finished_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state in ('queued','running','awaiting_approval','done','failed','partial')",
            name=op.f("ck_runs_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_runs_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_business_id"), "runs", ["business_id"], unique=False)
    op.create_index(op.f("ix_runs_state"), "runs", ["state"], unique=False)
    op.create_table(
        "actions",
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("external_ref", sa.String(length=512), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('in_flight','succeeded','failed','refused')",
            name=op.f("ck_actions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_actions_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_actions_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_actions_idempotency_key")),
    )
    op.create_index(op.f("ix_actions_business_id"), "actions", ["business_id"], unique=False)
    op.create_index(op.f("ix_actions_run_id"), "actions", ["run_id"], unique=False)
    op.create_table(
        "content_pieces",
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("surface", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=True),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seo_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("published_url", sa.String(length=2048), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('draft','needs_edit','approved','published','rejected')",
            name=op.f("ck_content_pieces_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_content_pieces_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_content_pieces_opportunity_id_opportunities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_content_pieces_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_pieces")),
    )
    op.create_index(
        op.f("ix_content_pieces_business_id"), "content_pieces", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_content_pieces_status"), "content_pieces", ["status"], unique=False)
    op.create_table(
        "kb_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_kb_chunks_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_kb_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_kb_chunks_document_id_ordinal"),
    )
    op.create_index(op.f("ix_kb_chunks_business_id"), "kb_chunks", ["business_id"], unique=False)
    op.create_index(op.f("ix_kb_chunks_content_hash"), "kb_chunks", ["content_hash"], unique=False)
    op.create_table(
        "model_usage",
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("node", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("usd", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_model_usage_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_model_usage_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_usage")),
    )
    op.create_index(
        op.f("ix_model_usage_business_id"), "model_usage", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_model_usage_run_id"), "model_usage", ["run_id"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_run_events_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_id_seq"),
    )
    op.create_index(op.f("ix_run_events_business_id"), "run_events", ["business_id"], unique=False)
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)

    # --- Row-level security -------------------------------------------------
    # Tenant isolation is a SCHEMA property here, not a code convention.
    #
    # FORCE is required because the application role owns these tables, and a
    # table owner bypasses its own policies without it.
    #
    # current_setting(..., true) returns NULL when the GUC is unset, so a
    # session that forgets to scope itself sees ZERO rows. That is the safe
    # direction -- but it also means a later data migration that UPDATEs one of
    # these tables will silently match nothing unless it wraps the write in
    # ALTER TABLE ... NO FORCE ROW LEVEL SECURITY / ... FORCE ROW LEVEL SECURITY.
    # Any cross-business read (admin views, nightly sweeps) must go through a
    # SECURITY DEFINER function rather than a weakened policy.
    op.execute("ALTER TABLE documents ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE documents FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON documents "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE kb_chunks ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE kb_chunks FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON kb_chunks "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE crawl_pages ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE crawl_pages FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON crawl_pages "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE runs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE runs FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON runs "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE run_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE run_events FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON run_events "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE model_usage ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE model_usage FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON model_usage "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE actions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE actions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON actions "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE opportunities ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE opportunities FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON opportunities "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )
    op.execute("ALTER TABLE content_pieces ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE content_pieces FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON content_pieces "
        "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
        "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
    )

    # Vector index for the Phase 3 knowledge base. HNSW rather than IVFFlat:
    # IVFFlat needs representative data at build time to pick its lists, and
    # this table is empty.
    op.execute(
        "CREATE INDEX ix_kb_chunks_embedding_hnsw ON kb_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_index(op.f("ix_run_events_business_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_model_usage_run_id"), table_name="model_usage")
    op.drop_index(op.f("ix_model_usage_business_id"), table_name="model_usage")
    op.drop_table("model_usage")
    op.drop_index(op.f("ix_kb_chunks_content_hash"), table_name="kb_chunks")
    op.drop_index(op.f("ix_kb_chunks_business_id"), table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_content_pieces_status"), table_name="content_pieces")
    op.drop_index(op.f("ix_content_pieces_business_id"), table_name="content_pieces")
    op.drop_table("content_pieces")
    op.drop_index(op.f("ix_actions_run_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_business_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_runs_state"), table_name="runs")
    op.drop_index(op.f("ix_runs_business_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_opportunities_score"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_business_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_documents_business_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_crawl_pages_business_id_url", table_name="crawl_pages")
    op.drop_index(op.f("ix_crawl_pages_business_id"), table_name="crawl_pages")
    op.drop_table("crawl_pages")
    op.drop_index(op.f("ix_businesses_owner_id"), table_name="businesses")
    op.drop_table("businesses")
    op.drop_table("users")
    # ### end Alembic commands ###
