"""model routes and provider settings

Revision ID: 5e08c8bea18d
Revises: 00d743800f3e
Create Date: 2026-08-19 09:25:00.646908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e08c8bea18d"
down_revision: Union[str, Sequence[str], None] = "00d743800f3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_routes",
        sa.Column("task_class", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column(
            "chain",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tier in ('cheap','mid','strong','embed')", name=op.f("ck_model_routes_tier_valid")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_model_routes_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_routes")),
        sa.UniqueConstraint("task_class", name=op.f("uq_model_routes_task_class")),
    )
    op.create_table(
        "provider_settings",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider in ('openrouter','anthropic','ollama','fake')",
            name=op.f("ck_provider_settings_provider_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_provider_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_settings")),
        sa.UniqueConstraint("provider", name=op.f("uq_provider_settings_provider")),
    )

    # NO row-level security on either table, and that is deliberate: neither carries a
    # business_id. Which model serves which task is an operator decision about cost and
    # quality, not customer data. The tenant-isolation suite derives its table list from
    # the ORM, so it will not expect a policy here.
    #
    # Seeded empty on purpose. An empty model_routes table means the router uses its
    # code defaults, so this migration changes no behaviour until an admin edits
    # something -- which is what makes it safe to deploy ahead of the admin screen.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_settings")
    op.drop_table("model_routes")
    # ### end Alembic commands ###
