"""lead loop, feedback, learned style, session revocation

Revision ID: 9281c4db5cd6
Revises: 1fc3f48597dc
Create Date: 2026-08-19 13:49:04.804290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9281c4db5cd6'
down_revision: Union[str, Sequence[str], None] = '1fc3f48597dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_style',
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('derived_from', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='proposed', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('proposed','approved','rejected')", name=op.f('ck_learned_style_status_valid')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_learned_style_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learned_style'))
    )
    op.create_index(op.f('ix_learned_style_business_id'), 'learned_style', ['business_id'], unique=False)
    op.create_table('feedback',
    sa.Column('content_piece_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('axes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict in ('approved','rejected')", name=op.f('ck_feedback_verdict_valid')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_feedback_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], name=op.f('fk_feedback_content_piece_id_content_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_business_id'), 'feedback', ['business_id'], unique=False)
    op.create_index(op.f('ix_feedback_content_piece_id'), 'feedback', ['content_piece_id'], unique=False)
    op.create_table('short_links',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('content_piece_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('campaign', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_short_links_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], name=op.f('fk_short_links_content_piece_id_content_pieces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_links')),
    sa.UniqueConstraint('code', name=op.f('uq_short_links_code'))
    )
    op.create_index(op.f('ix_short_links_business_id'), 'short_links', ['business_id'], unique=False)
    op.create_index(op.f('ix_short_links_content_piece_id'), 'short_links', ['content_piece_id'], unique=False)
    op.create_table('leads',
    sa.Column('content_piece_id', sa.UUID(), nullable=True),
    sa.Column('short_link_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), server_default='form', nullable=False),
    sa.Column('utm', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_leads_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], name=op.f('fk_leads_content_piece_id_content_pieces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['short_link_id'], ['short_links.id'], name=op.f('fk_leads_short_link_id_short_links'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_content_piece_id'), 'leads', ['content_piece_id'], unique=False)
    op.create_table('link_clicks',
    sa.Column('short_link_id', sa.UUID(), nullable=False),
    sa.Column('referrer_host', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_link_clicks_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['short_link_id'], ['short_links.id'], name=op.f('fk_link_clicks_short_link_id_short_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_clicks'))
    )
    op.create_index(op.f('ix_link_clicks_business_id'), 'link_clicks', ['business_id'], unique=False)
    op.create_index(op.f('ix_link_clicks_short_link_id'), 'link_clicks', ['short_link_id'], unique=False)
    op.add_column('users', sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True))

    # Every new table here is business-scoped, so every one needs RLS. ENABLE alone is
    # not enough: the app role owns these tables and an owner bypasses its own policies
    # without FORCE. The isolation suite derives its list from the ORM, so a table added
    # without a policy fails the build rather than leaking quietly.
    for table in ("short_links", "link_clicks", "leads", "feedback", "learned_style"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (business_id = current_setting('app.current_business_id', true)::uuid) "
            "WITH CHECK (business_id = current_setting('app.current_business_id', true)::uuid)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_valid_from')
    op.drop_index(op.f('ix_link_clicks_short_link_id'), table_name='link_clicks')
    op.drop_index(op.f('ix_link_clicks_business_id'), table_name='link_clicks')
    op.drop_table('link_clicks')
    op.drop_index(op.f('ix_leads_content_piece_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_short_links_content_piece_id'), table_name='short_links')
    op.drop_index(op.f('ix_short_links_business_id'), table_name='short_links')
    op.drop_table('short_links')
    op.drop_index(op.f('ix_feedback_content_piece_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_business_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_learned_style_business_id'), table_name='learned_style')
    op.drop_table('learned_style')
    # ### end Alembic commands ###
