"""platform connections, with the credential encrypted and RLS from day one

Revision ID: d4f18a6c93b7
Revises: c7a41d92b6f0
Create Date: 2026-08-20 10:40:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4f18a6c93b7"
down_revision: Union[str, Sequence[str], None] = "c7a41d92b6f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create ``platform_connections``.

    Written by hand rather than autogenerated, because the two most important lines in
    this file -- ``FORCE ROW LEVEL SECURITY`` and the null-safe tenant policy -- are ones
    autogenerate does not know about.

    Two columns hold ciphertext (``credential_encrypted``,
    ``refresh_credential_encrypted``) and NOTHING here holds a key: the key comes from
    the environment (``core/token_cipher``), because a key stored beside the ciphertext
    it protects protects nothing. Both are nullable so that a revoke can forget the
    credential in place rather than leaving it decryptable in a row marked dead.

    ``credential_hint`` is the masked prefix/suffix every read path returns instead. It
    is 64 characters, which is far more than the eight-plus-ellipsis it holds today, so a
    future hint format does not need a migration.
    """
    op.create_table(
        "platform_connections",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_account_id", sa.String(length=255), nullable=False),
        sa.Column("external_account_name", sa.String(length=255), nullable=True),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="connected", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credential_scheme", sa.String(length=32), server_default="", nullable=False),
        sa.Column("credential_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_credential_encrypted", sa.Text(), nullable=True),
        sa.Column("credential_hint", sa.String(length=64), server_default="", nullable=False),
        sa.Column("fake", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('connected','expired','revoked')",
            name=op.f("ck_platform_connections_status_valid"),
        ),
        # The closed platform list, mirroring `services.platform_oauth
        # .CONNECTABLE_PLATFORMS`. A typo'd platform is a connection nobody can ever
        # publish through, so this turns it into an insert failure rather than a support
        # ticket. Widening the list is deliberately a migration.
        sa.CheckConstraint(
            "platform in ('facebook','instagram','linkedin','tiktok','youtube','google_business')",
            name=op.f("ck_platform_connections_platform_known"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_platform_connections_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_connections")),
        sa.UniqueConstraint(
            "business_id",
            "platform",
            "external_account_id",
            name=op.f("uq_platform_connections_business_id_platform_external_account_id"),
        ),
    )
    op.create_index(
        op.f("ix_platform_connections_business_id"),
        "platform_connections",
        ["business_id"],
        unique=False,
    )
    # The publish path asks exactly one question of this table -- "does this business
    # have a usable connection to this platform" -- so that is the index it gets.
    op.create_index(
        "ix_platform_connections_business_platform",
        "platform_connections",
        ["business_id", "platform"],
        unique=False,
    )

    # Business-scoped, so row-level security, from the first migration that creates the
    # table rather than from a later one that remembers. ENABLE alone is not enough: the
    # role that owns this table would bypass its own policy without FORCE.
    #
    # `nullif(..., '')` rather than a bare cast, per migration 5b532c05f131: `set_config`
    # is transaction-local, so at COMMIT the GUC becomes the EMPTY STRING rather than
    # unset, and `''::uuid` raises instead of denying. The whole design of these policies
    # is that forgetting to scope a session shows nothing, safely.
    op.execute("ALTER TABLE platform_connections ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE platform_connections FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON platform_connections "
        "USING (business_id = nullif(current_setting('app.current_business_id', true), '')::uuid) "
        "WITH CHECK (business_id = nullif(current_setting('app.current_business_id', true), '')::uuid)"
    )


def downgrade() -> None:
    """Drop the table. The policy goes with it, which is why it is not dropped first."""
    op.drop_index("ix_platform_connections_business_platform", table_name="platform_connections")
    op.drop_index(op.f("ix_platform_connections_business_id"), table_name="platform_connections")
    op.drop_table("platform_connections")
