"""scheduling: social_posts and automation_settings, both with RLS from day one

`social_posts` is the shape `docs/ROADMAP.md` section 6 specifies, plus the columns a
row needs in order to be publishable rather than merely rendered: `business_id` (every
business-scoped table carries one), `published_at`, and `action_id` -- the join to the
idempotency record that makes a publish safe to retry.

`automation_settings` is one standing instruction per business: cadence, local day and
hour, IANA zone, and the cached `next_run_at` the scheduler's due-work query scans.

Both tables are business-scoped, so both get ENABLE + FORCE ROW LEVEL SECURITY and the
null-safe tenant policy in the same migration that creates them -- not in a later one
that remembers.

The restricted ``sma_app`` role reaches both through the ``ALTER DEFAULT PRIVILEGES``
grant installed by ``8ee986b398e9``, so no explicit GRANT is needed here.

Revision ID: f2a7d61b40c8
Revises: a1c9e4f27b31
Create Date: 2026-08-21 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f2a7d61b40c8"
down_revision: Union[str, Sequence[str], None] = "a1c9e4f27b31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCOPED_TABLES = ("social_posts", "automation_settings")


def _enable_rls(table: str) -> None:
    """ENABLE + FORCE + the null-safe tenant policy, for one table.

    Three lines, each of which has been got wrong somewhere in this project's history:

    * **ENABLE alone is not enough.** The role that owns the table bypasses its own
      policy without FORCE, and every migration here runs as the owner -- so a table
      with ENABLE and no FORCE looks protected in `pg_policies` and is not.
    * **`nullif(..., '')` rather than a bare cast**, per migration `5b532c05f131`.
      `set_config(..., true)` is transaction-local, so at COMMIT the GUC becomes the
      EMPTY STRING rather than unset, and `''::uuid` raises instead of denying. The whole
      design of these policies is that forgetting to scope a session shows nothing,
      safely -- an exception inverts that into an outage.
    * **WITH CHECK as well as USING.** USING filters reads, updates and deletes; without
      WITH CHECK a session scoped to business B can still INSERT a row carrying business
      A's id, which is a forged row rather than a leaked one.
    """
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        "USING (business_id = nullif(current_setting('app.current_business_id', true), '')::uuid) "
        "WITH CHECK (business_id = nullif(current_setting('app.current_business_id', true), '')::uuid)"
    )


def upgrade() -> None:
    """Create both tables.

    Written by hand rather than autogenerated, because the lines that matter most here --
    FORCE ROW LEVEL SECURITY and the null-safe policy -- are ones autogenerate does not
    know about.

    No UPDATE or DELETE runs anywhere in this function, so no `NO FORCE ROW LEVEL
    SECURITY` toggle is needed (see `e6a1c3f5b28d`'s downgrade for that hazard in full:
    `app.current_business_id` is unset inside a migration, so a bare write on a FORCE-RLS
    table silently affects zero rows while reporting success). New tables have no rows to
    backfill, and every added column carries a server default, which is what keeps it
    that way.
    """
    op.create_table(
        "social_posts",
        sa.Column("content_piece_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "hashtags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "utm",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # `refused` (our approval policy said no) is kept apart from `failed` (the
        # platform said no), because a retry is correct for one and is a policy violation
        # for the other. Same split `actions.status` already draws.
        sa.CheckConstraint(
            "status in ('queued','scheduled','published','failed','refused','cancelled')",
            name=op.f("ck_social_posts_status_valid"),
        ),
        # CASCADE, and the column is NOT NULL: a channel rendering has no meaning without
        # the piece it renders, and a scheduled post pointing at a deleted piece is how
        # something gets published for content nobody owns any more.
        sa.ForeignKeyConstraint(
            ["content_piece_id"],
            ["content_pieces.id"],
            name=op.f("fk_social_posts_content_piece_id_content_pieces"),
            ondelete="CASCADE",
        ),
        # SET NULL, deliberately not CASCADE: an action is an audit row, and taking the
        # post with it would destroy the more valuable of the two.
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
            name=op.f("fk_social_posts_action_id_actions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_social_posts_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_posts")),
    )
    op.create_index(
        op.f("ix_social_posts_business_id"), "social_posts", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_social_posts_content_piece_id"),
        "social_posts",
        ["content_piece_id"],
        unique=False,
    )
    # The publisher asks this table exactly one question -- "what is due" -- so that is
    # the index it gets. Status leads because it is the selective half: everything ever
    # published stays in the table forever and must not be re-scanned to find it isn't due.
    op.create_index(
        "ix_social_posts_status_scheduled_at",
        "social_posts",
        ["status", "scheduled_at"],
        unique=False,
    )

    op.create_table(
        "automation_settings",
        sa.Column("mode", sa.String(length=32), server_default="off", nullable=False),
        sa.Column("cadence", sa.String(length=16), server_default="weekly", nullable=False),
        sa.Column("day_of_week", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("hour", sa.Integer(), server_default=sa.text("9"), nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Berlin", nullable=False),
        sa.Column(
            "channels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("goal_template", sa.Text(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # `off` is the default and `scheduled_draft` is the ceiling in this build. There
        # is no `scheduled_publish`: publishing without a human is an approval-policy
        # decision, and a value here would let a settings write grant a capability the
        # policy table owns.
        sa.CheckConstraint(
            "mode in ('off','scheduled_draft')", name=op.f("ck_automation_settings_mode_valid")
        ),
        sa.CheckConstraint(
            "cadence in ('weekly','biweekly','monthly')",
            name=op.f("ck_automation_settings_cadence_valid"),
        ),
        # Monday=0 .. Sunday=6, matching `date.weekday()`. The range CHECK exists because
        # `day_of_week = 7` is the ISO-vs-Python off-by-one arriving as data, and without
        # it that row matches no weekday and therefore silently never runs.
        sa.CheckConstraint(
            "day_of_week between 0 and 6",
            name=op.f("ck_automation_settings_day_of_week_valid"),
        ),
        sa.CheckConstraint("hour between 0 and 23", name=op.f("ck_automation_settings_hour_valid")),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_automation_settings_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_settings")),
        # One standing instruction per business. Two rows would be two answers to "when
        # does this business publish", and the scheduler would honour whichever one the
        # planner happened to return first.
        sa.UniqueConstraint("business_id", name=op.f("uq_automation_settings_business_id")),
    )
    # Subsumed by the unique constraint above for lookup purposes, and created anyway so
    # the ORM metadata (`BusinessScopedMixin` declares `index=True`) and the database
    # agree. A schema that differs from the models is how a later autogenerate produces a
    # migration nobody asked for.
    op.create_index(
        op.f("ix_automation_settings_business_id"),
        "automation_settings",
        ["business_id"],
        unique=False,
    )
    # The scheduler's due-work query is `next_run_at <= now()` across businesses, so it
    # gets its own index rather than a scan of every settings row.
    op.create_index(
        op.f("ix_automation_settings_next_run_at"),
        "automation_settings",
        ["next_run_at"],
        unique=False,
    )

    for table in _SCOPED_TABLES:
        _enable_rls(table)


def downgrade() -> None:
    """Drop both tables. The policies go with them, which is why they are not dropped
    first -- and losing which posts were scheduled or when automation next runs is
    unreconstructable, so this is lossy on purpose rather than by oversight."""
    op.drop_index(op.f("ix_automation_settings_next_run_at"), table_name="automation_settings")
    op.drop_index(op.f("ix_automation_settings_business_id"), table_name="automation_settings")
    op.drop_table("automation_settings")

    op.drop_index("ix_social_posts_status_scheduled_at", table_name="social_posts")
    op.drop_index(op.f("ix_social_posts_content_piece_id"), table_name="social_posts")
    op.drop_index(op.f("ix_social_posts_business_id"), table_name="social_posts")
    op.drop_table("social_posts")
